namespace GeneratedModels
{
    public class CargoAWB
    {
        public int AWBID { get; set; }
        public int CargoID { get; set; }
        public bool isDeleted { get; set; }
        public string KGLB { get; set; }
        public int? DocumentTypeID { get; set; }
        public string DocumentType { get; set; }
        public string HeadLeft { get; set; }
        public string HeadCenter { get; set; }
        public string HeadRight { get; set; }
        public string MasterAWBNumber { get; set; }
        public string HouseAWBNumber { get; set; }
        public string AWBIssuedBy { get; set; }
        public int? ShipperAddressID { get; set; }
        public string ShipperName { get; set; }
        public string ShipperAddress { get; set; }
        public int? ConsigneeAddressID { get; set; }
        public string ConsigneeName { get; set; }
        public string ConsigneeAddress { get; set; }
        public string IssuingCarrierAddress { get; set; }
        public string AgentsIATACode { get; set; }
        public string AccountNo { get; set; }
        public string AccountingInformation { get; set; }
        public string AirportOfDeparture { get; set; }
        public string Reference1 { get; set; }
        public string Reference2 { get; set; }
        public string Reference3 { get; set; }
        public string RoutingTo1 { get; set; }
        public string ByFirstCarrier { get; set; }
        public string To2 { get; set; }
        public string By2 { get; set; }
        public string To3 { get; set; }
        public string By3 { get; set; }
        public string AirportOfDestination { get; set; }
        public string RequestedFlight1 { get; set; }
        public string RequestedFlight2 { get; set; }
        public string CurrencyCode { get; set; }
        public string CGHSCode { get; set; }
        public bool? WTValPPD { get; set; }
        public bool? WTValCOLL { get; set; }
        public bool? OtherPPD { get; set; }
        public bool? OtherCOLL { get; set; }
        public string DeclaredValueForCarriage { get; set; }
        public string DeclaredValueForCustoms { get; set; }
        public string HandlingInformation { get; set; }
        public string SCI { get; set; }
        public int? NoOfPieces { get; set; }
        public decimal? GrossWeight { get; set; }
        public int? WeightUnitID { get; set; }
        public string RateClass { get; set; }
        public decimal? ChargeableWeight { get; set; }
        public decimal? RateCharge { get; set; }
        public decimal? TotalAmount { get; set; }
        public string NatureAndQuantityOfGoods { get; set; }
        public decimal? WeightChargePPD { get; set; }
        public decimal? WeightChargeCOLL { get; set; }
        public decimal? ValuationPPD { get; set; }
        public decimal? ValuationCOLL { get; set; }
        public decimal? TaxPPD { get; set; }
        public decimal? TaxCOLL { get; set; }
        public decimal? DueAgentPPD { get; set; }
        public decimal? DueAgentCOLL { get; set; }
        public decimal? DueCarrierPPD { get; set; }
        public decimal? DueCarrierCOLL { get; set; }
        public decimal? TotalPPD { get; set; }
        public decimal? TotalCOLL { get; set; }
        public string CurrencyConversionRates { get; set; }
        public decimal? CCDestCurrency { get; set; }
        public decimal? ChargesAtDestination { get; set; }
        public decimal? TotalCollectCharges { get; set; }
        public string OtherCharges { get; set; }
        public string SignatureOfShipper { get; set; }
        public DateTime? ExecutedOn { get; set; }
        public string ExecutedPlace { get; set; }
        public string SignatureOfIssuingCarrier { get; set; }
        public string Description1 { get; set; }
        public string Description2 { get; set; }
        public int? CreatedBy { get; set; }
        public string? CreatedByName { get; set; }
        public DateTime? DateCreated { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? DateModified { get; set; }
        public int? DeletedBy { get; set; }
        public DateTime? DateDeleted { get; set; }
    }
}
