namespace GeneratedModels
{
    public class SalesQuotes
    {
        public bool isDeleted { get; set; }
        public bool isContract { get; set; }
        public int SalesQuoteID { get; set; }
        public string SalesQuoteNumber { get; set; }
        public int CompanyID { get; set; }
        public int ContactID { get; set; }
        public int PreparedBy { get; set; }
        public int SalesPersonID { get; set; }
        public bool isRejected { get; set; }
        public int TypeOfMoveID { get; set; }
        public bool isDraft { get; set; }
        public bool isApproved { get; set; }
        public DateTime? ApprovedDate { get; set; }
        public int? IncoTermID { get; set; }
        public int? OldSalesQuoteID { get; set; }
        public int? RevisionID { get; set; }
        public int? FileID { get; set; }
        public DateTime? RejectedDate { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? DateCreated { get; set; }
        public int? ModifiedBy { get; set; }
        public DateTime? DateModified { get; set; }
        public int? DeletedBy { get; set; }
        public DateTime? DateDeleted { get; set; }
        public DateTime? SalesQuoteDate { get; set; }
        public DateTime? ExpiryDate { get; set; }
        public string ContractNumber { get; set; }
        public int? PlaceOfOriginID { get; set; }
        public string PlaceOfOrigin { get; set; }
        public int? POLID { get; set; }
        public string POL { get; set; }
        public int? POT1ID { get; set; }
        public string POT1 { get; set; }
        public int? POT2ID { get; set; }
        public string POT2 { get; set; }
        public int? POT3ID { get; set; }
        public string POT3 { get; set; }
        public int? PODID { get; set; }
        public string POD { get; set; }
        public int? PlaceOfDeliveryID { get; set; }
        public string PlaceOfDelivery { get; set; }
        public int? PickupAddressID { get; set; }
        public string PickupAddress { get; set; }
        public string PickupAddressStreet { get; set; }
        public string PickupAddressCity { get; set; }
        public string PickupAddressState { get; set; }
        public string PickupAddressCountry { get; set; }
        public string PickupAddressZip { get; set; }
        public int? DeliveryAddressID { get; set; }
        public string DeliveryAddress { get; set; }
        public string DeliveryAddressStreet { get; set; }
        public string DeliveryAddressCity { get; set; }
        public string DeliveryAddressState { get; set; }
        public string DeliveryAddressCountry { get; set; }
        public string DeliveryAddressZip { get; set; }
        public string Frequency { get; set; }
        public int? CarrierID { get; set; }
        public string Carrier { get; set; }
        public int? CarrierAgentID { get; set; }
        public string CarrierAgent { get; set; }
        public bool? isHazardous { get; set; }
        public string Commodity { get; set; }
        public decimal? CommodityValue { get; set; }
        public int? CommodityValueCurrencyID { get; set; }
        public string CommodityValueCurrency { get; set; }
        public string RequiredEquipment { get; set; }
        public decimal? GrossWeight { get; set; }
        public decimal? Volume { get; set; }
        public decimal? VolumeWeight { get; set; }
        public decimal? ChargeableWeight { get; set; }
        public string CompanyDisplayName { get; set; }
        public string ContactDisplayName { get; set; }
        public string SalesPersonDisplayName { get; set; }
        public string PreparedByDislayName { get; set; }
        public string EmailTo { get; set; }
        public string EmailCC { get; set; }
        public string ContactEmail { get; set; }
        public string ContactTelephone { get; set; }
        public string IncoTerm { get; set; }
        public string TypeOfMove { get; set; }
        public string InternalNotes { get; set; }
        public string CustomerNotes { get; set; }
        public bool? showLiner { get; set; }
        public int? SalesQuoteCurrencyID { get; set; }
        public string SalesQuoteCurrency { get; set; }
        public int? SalesQuoteBaseCurrencyID { get; set; }
        public string SalesQuoteBaseCurrency { get; set; }
        public bool? showAllIn { get; set; }
        public decimal? SalesQuoteExRate { get; set; }
        public decimal? SalesQuoteExRateInverse { get; set; }
        public int? OfficeID { get; set; }
        public int? OpportunityID { get; set; }
        public string SalesQuoteType { get; set; }
    }
}
